version: 2
jobs:
  test:
    docker:
      - image: circleci/golang:1.11.2
    environment:
      GOPATH: /home/circleci/.go_workspace
    working_directory: /home/circleci/.go_workspace/src/github.com/loadimpact/k6
    steps:
      - checkout
      - run:
          name: Run tests and code coverage
          command: |
            export GOMAXPROCS=4
            export PATH=$GOPATH/bin:$PATH
            ulimit -a
            go test -v -race -timeout 600s   ./stats/datadog/...

workflows:
  version: 2
  test_and_build:
    jobs:
      - test:
          filters:
            tags:
              only: /.*/
